package com.loverofdarkness.remotebtkeyboard;

import android.annotation.SuppressLint;
import android.bluetooth.*;
import android.content.Context;
import android.os.Handler;
import android.os.HandlerThread;
import android.os.PowerManager;
import android.util.Log;
import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;

@SuppressLint("MissingPermission")
public final class HidController implements BluetoothProfile.ServiceListener {
    public enum State { IDLE, SEARCHING, SELECTED, REGISTERING, CONNECTING, CONNECTED, DISCONNECTING, DISCONNECTED, ERROR }
    public static final class DeviceRow { public final String address,name; DeviceRow(BluetoothDevice d){address=d.getAddress(); name=safeName(d);} }
    public static final class Snapshot {
        public final State state; public final String selectedName,message,draft; public final boolean connected,live,busy; public final List<DeviceRow> devices; public final int modifiers;
        Snapshot(State s,String n,String m,String d,boolean c,boolean l,boolean b,List<DeviceRow> rows,int mod){state=s;selectedName=n;message=m;draft=d;connected=c;live=l;busy=b;devices=Collections.unmodifiableList(new ArrayList<>(rows));modifiers=mod;}
    }
    private final Context context; private final BluetoothAdapter adapter; private final HandlerThread thread=new HandlerThread("DevilBT-HID"); private final Handler h; private final PowerManager.WakeLock wake; private final List<java.util.function.Consumer<Snapshot>> observers=new CopyOnWriteArrayList<>();
    private BluetoothHidDevice hid; private final LinkedHashMap<String,BluetoothDevice> candidates=new LinkedHashMap<>(); private BluetoothDevice selected,host; private State state=State.IDLE; private String message="Press Search Devices."; private boolean registered,registering,wanted,connected,disconnecting,closed; private int modifiers; private boolean live=true; private String draft="",remote=""; private EditPlan plan; private String jobText; private int jobIndex; private KeyCodec.Stroke pendingStroke; private Runnable strokeDone; private long epoch;
    private final BluetoothHidDevice.Callback callback=new BluetoothHidDevice.Callback(){
        @Override public void onAppStatusChanged(BluetoothDevice plugged, boolean ok){ exec(()->{ registering=false; registered=ok; if(!ok){ connected=false; host=null; if(wanted&&!disconnecting) fail("HID registration failed."); else publish(); return; } publish(); if(wanted && selected!=null) advance(); else if(!wanted) unregister(); }); }
        @Override public void onConnectionStateChanged(BluetoothDevice d,int s){ exec(()->handleConnection(d,s)); }
        @Override public void onGetReport(BluetoothDevice d,byte type,byte id,int size){ exec(()->{ if(!same(d,host)||id!=0){ if(hid!=null) hid.reportError(d,BluetoothHidDevice.ERROR_RSP_INVALID_RPT_ID); return;} byte[] data; if(type==BluetoothHidDevice.REPORT_TYPE_INPUT)data=KeyCodec.release(); else if(type==BluetoothHidDevice.REPORT_TYPE_OUTPUT)data=new byte[]{0}; else {hid.reportError(d,BluetoothHidDevice.ERROR_RSP_UNSUPPORTED_REQ);return;} if(size>0&&size<data.length){hid.reportError(d,BluetoothHidDevice.ERROR_RSP_INVALID_PARAM);return;} hid.replyReport(d,type,id,data); }); }
        @Override public void onSetReport(BluetoothDevice d,byte type,byte id,byte[] data){ }
        @Override public void onSetProtocol(BluetoothDevice d,byte protocol){ }
        @Override public void onVirtualCableUnplug(BluetoothDevice d){ exec(()->{if(same(d,selected)) loss("Host removed the virtual cable.");}); }
    };
    public HidController(Context c){ context=c.getApplicationContext(); BluetoothManager bm=context.getSystemService(BluetoothManager.class); adapter=bm==null?null:bm.getAdapter(); PowerManager pm=context.getSystemService(PowerManager.class); wake=pm==null?null:pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"DevilRemoteBTKeyboard:input"); if(wake!=null)wake.setReferenceCounted(false); thread.start(); h=new Handler(thread.getLooper()); exec(()->{if(adapter==null){fail("Bluetooth unavailable.");}else if(!adapter.isEnabled()){state=State.DISCONNECTED;message="Bluetooth is off.";publish();}else acquire();}); }
    public void observe(java.util.function.Consumer<Snapshot> o){observers.add(o); publishFromCurrent(o);}
    private void publishFromCurrent(java.util.function.Consumer<Snapshot> o){o.accept(snapshot());}
    private void exec(Runnable r){if(closed)return; h.post(()->{try{r.run();}catch(SecurityException e){fail("Bluetooth permission denied.");}catch(RuntimeException e){Log.e("DevilRemoteBT", "controller error",e);fail("Bluetooth operation failed.");}});}
    private void later(long ms,Runnable r){if(closed)return;h.postDelayed(()->{if(!closed)try{r.run();}catch(RuntimeException e){Log.e("DevilRemoteBT","scheduled error",e);fail("Bluetooth operation failed.");}},ms);}
    private Snapshot snapshot(){return new Snapshot(state,selected==null?"None":safeName(selected),message,draft,connected,live,pendingStroke!=null||jobText!=null,rows(),modifiers);}
    private void publish(){Snapshot s=snapshot();for(var o:observers)o.accept(s);}
    private List<DeviceRow> rows(){List<DeviceRow> r=new ArrayList<>();for(BluetoothDevice d:candidates.values())r.add(new DeviceRow(d));return r;}
    private static String safeName(BluetoothDevice d){try{String n=d.getName();return n==null||n.isBlank()?"Bluetooth device":n;}catch(Exception e){return "Bluetooth device";}}
    private static boolean same(BluetoothDevice a,BluetoothDevice b){return a!=null&&b!=null&&a.getAddress().equals(b.getAddress());}
    private boolean computer(BluetoothDevice d){BluetoothClass c=d.getBluetoothClass();return c!=null&&c.getMajorDeviceClass()==BluetoothClass.Device.Major.COMPUTER;}
    private void acquire(){if(adapter==null||!adapter.isEnabled())return;if(hid==null){try{adapter.getProfileProxy(context,this,BluetoothProfile.HID_DEVICE);}catch(Exception e){fail("Could not open HID profile.");}}}
    @Override public void onServiceConnected(int p,BluetoothProfile proxy){exec(()->{if(p==BluetoothProfile.HID_DEVICE){hid=(BluetoothHidDevice)proxy;refreshCandidates();advance();}else refreshCandidates();});}
    @Override public void onServiceDisconnected(int p){exec(()->{if(p==BluetoothProfile.HID_DEVICE){hid=null;registered=false;registering=false;connected=false;host=null;if(wanted)loss("HID service disappeared.");else{state=State.DISCONNECTED;message="HID service unavailable.";publish();}}});}
    public void search(){exec(()->{if(adapter==null||!adapter.isEnabled()){state=State.DISCONNECTED;message="Enable Bluetooth first.";publish();return;}state=State.SEARCHING;message="Searching paired Bluetooth computers…";publish();acquire();refreshCandidates();state=selected==null?State.DISCONNECTED:State.SELECTED;message=candidates.isEmpty()?"No paired Bluetooth computers found. Pair your laptop first.":"Select your laptop below, then Connect.";publish();});}
    private void refreshCandidates(){candidates.clear();if(adapter==null||!adapter.isEnabled())return;for(BluetoothDevice d:adapter.getBondedDevices())if(computer(d))candidates.put(d.getAddress(),d);if(hid!=null)for(BluetoothDevice d:hid.getConnectedDevices())if(computer(d))candidates.put(d.getAddress(),d);}
    public void aclChanged(BluetoothDevice d,boolean on){exec(()->{if(d==null)return;if(on&&computer(d))candidates.put(d.getAddress(),d);else if(!on){boolean paired=false;try{for(BluetoothDevice x:adapter.getBondedDevices())if(same(x,d)){paired=true;break;}}catch(Exception ignored){}if(!paired)candidates.remove(d.getAddress());}if(!on&&same(d,selected)&&wanted)loss("Selected computer disconnected.");publish();});}
    public void select(String address){exec(()->{if(wanted||connected){message="Disconnect before changing device.";publish();return;}refreshCandidates();BluetoothDevice d=candidates.get(address);if(d==null){message="Device is no longer paired or available.";publish();return;}selected=d;state=State.SELECTED;message="Selected "+safeName(d)+". Press Connect.";publish();});}
    public void connect(){exec(()->{if(wanted||connected)return;if(adapter==null||!adapter.isEnabled()){message="Enable Bluetooth first.";publish();return;}if(selected==null){message="Search and select a computer first.";publish();return;}refreshCandidates();if(!candidates.containsKey(selected.getAddress())){message="Selected computer is no longer paired or available.";publish();return;}wanted=true;disconnecting=false;state=State.CONNECTING;message="Preparing Bluetooth HID…";publish();acquire();advance();later(30000,()->{if(wanted&&!connected)fail("Connection timed out. Try Connect again.");});});}
    private void advance(){if(closed||!wanted||selected==null||connected||hid==null)return;if(!registered){if(registering)return;registering=true;state=State.REGISTERING;publish();BluetoothHidDeviceAppSdpSettings s=new BluetoothHidDeviceAppSdpSettings("Devil RemoteBT Keyboard","Bluetooth keyboard","Devil RemoteBT Keyboard",BluetoothHidDevice.SUBCLASS1_KEYBOARD,KeyCodec.descriptor());if(!hid.registerApp(s,null,null,h::post,callback)){registering=false;fail("HID registration request rejected.");}return;}if(!same(selected,host)){state=State.CONNECTING;message="Connecting to "+safeName(selected)+"…";publish();if(!hid.connect(selected))fail("HID connection request rejected.");}}
    private void handleConnection(BluetoothDevice d,int s){if(!same(d,selected)){if(s==BluetoothProfile.STATE_CONNECTED||s==BluetoothProfile.STATE_CONNECTING)hid.disconnect(d);return;}if(s==BluetoothProfile.STATE_CONNECTING){state=State.CONNECTING;message="Connecting to "+safeName(d)+"…";publish();}else if(s==BluetoothProfile.STATE_CONNECTED){if(connected)return;host=d;connected=true;epoch++;remote="";draft="";plan=null;state=State.CONNECTED;message="Connected. Ready to type.";publish();}else if(s==BluetoothProfile.STATE_DISCONNECTED){loss("Computer disconnected.");}}
    public void disconnect(){exec(()->{wanted=false;disconnecting=true;epoch++;cancelInput();modifiers=0;BluetoothDevice d=host!=null?host:selected;if(hid!=null&&d!=null&&registered)hid.disconnect(d);connected=false;host=null;state=State.DISCONNECTING;message="Disconnecting…";publish();later(1500,()->finishDisconnect());});}
    private void finishDisconnect(){if(disconnecting){disconnecting=false;unregister();state=State.DISCONNECTED;message="Disconnected.";publish();}}
    private void unregister(){if(hid!=null&&(registered||registering)){registering=true;try{if(!hid.unregisterApp()){registering=false;registered=false;}}catch(Exception e){registering=false;registered=false;}}}
    private void loss(String why){wanted=false;disconnecting=false;epoch++;cancelInput();connected=false;host=null;modifiers=0;if(hid!=null&&registered)hid.disconnect(selected);unregister();state=State.DISCONNECTED;message=why;publish();}
    private void fail(String why){wanted=false;disconnecting=false;epoch++;cancelInput();connected=false;host=null;state=State.ERROR;message=why;publish();}
    private void cancelInput(){pendingStroke=null;strokeDone=null;jobText=null;jobIndex=0;plan=null;if(wake!=null&&wake.isHeld())wake.release();}
    public void setLive(boolean on){exec(()->{if(pendingStroke!=null||jobText!=null){message="Finish the current send before changing mode.";publish();return;}live=on;remote="";plan=null;message=on?"Live mode enabled.":"Buffered mode enabled.";publish();});}
    public void setDraft(String text){exec(()->{if(!connected){draft=text;publish();return;}if(text.length()>20000){message="Text is too long.";publish();return;}draft=text;String target;try{target=KeyCodec.normalize(text);}catch(Exception e){message=e.getMessage();publish();return;}if(live)scheduleSync(target);publish();});}
    private void scheduleSync(String target){if(!connected)return;final long e=epoch;h.post(()->pumpLive(target,e));}
    private void pumpLive(String target,long e){if(closed||e!=epoch||!connected)return;if(pendingStroke!=null){later(8,()->pumpLive(target,e));return;}if(!remote.equals(target)){if(plan==null||!plan.target.equals(target))plan=new EditPlan(remote,target);if(plan.deletes>0){tap(new KeyCodec.Stroke(KeyCodec.BACKSPACE,0),()->{if(remote.length()>0)remote=remote.substring(0,remote.length()-1);plan.deletes--;pumpLive(target,e);});return;}if(plan.index<target.length()){char c=target.charAt(plan.index);tap(KeyCodec.charStroke(c,false),()->{remote+=c;plan.index++;pumpLive(target,e);});return;}}}
    public void sendBuffer(){exec(()->{if(!connected||live||jobText!=null)return;final String t;try{t=KeyCodec.normalize(draft);}catch(Exception e){message=e.getMessage();publish();return;}if(t.isEmpty())return;jobText=t;jobIndex=0;startWake();pumpJob();});}
    private void pumpJob(){if(!connected||jobText==null||pendingStroke!=null)return;if(jobIndex>=jobText.length()){jobText=null;releaseWake();message="Buffer sent to Bluetooth stack.";publish();return;}tap(KeyCodec.charStroke(jobText.charAt(jobIndex),false),()->{jobIndex++;pumpJob();});}
    public void special(int usage,int baseMod){exec(()->{if(!connected)return;final int m=baseMod|modifiers;modifiers=0;final String flush=live?draft:"";if(live&&!flush.isEmpty()){jobText=null;final String t;try{t=KeyCodec.normalize(flush);}catch(Exception e){message=e.getMessage();publish();return;}final long e=epoch;syncThen(t,e,()->tap(new KeyCodec.Stroke(usage,m),()->{draft="";remote="";plan=null;publish();}));}else tap(new KeyCodec.Stroke(usage,m),()->publish());});}
    private void syncThen(String t,long e,Runnable done){if(!connected||e!=epoch)return;if(!remote.equals(t)){if(pendingStroke!=null){later(8,()->syncThen(t,e,done));return;}if(plan==null||!plan.target.equals(t))plan=new EditPlan(remote,t);if(plan.deletes>0){tap(new KeyCodec.Stroke(KeyCodec.BACKSPACE,0),()->{remote=remote.substring(0,remote.length()-1);plan.deletes--;syncThen(t,e,done);});return;}if(plan.index<t.length()){char c=t.charAt(plan.index);tap(KeyCodec.charStroke(c,false),()->{remote+=c;plan.index++;syncThen(t,e,done);});return;}}plan=null;done.run();}
    public void modifier(int mask){exec(()->{if(connected){modifiers^=mask;publish();}});}
    private void startWake(){if(wake!=null&&!wake.isHeld())wake.acquire(15000);}
    private void releaseWake(){if(wake!=null&&wake.isHeld())wake.release();}
    private void tap(KeyCodec.Stroke s,Runnable done){if(pendingStroke!=null)throw new IllegalStateException("HID stroke overlap");pendingStroke=s;strokeDone=done;startWake();emit(KeyCodec.report(s.modifiers,s.usage),()->{emit(KeyCodec.release(),()->{Runnable r=strokeDone;pendingStroke=null;strokeDone=null;if(r!=null)r.run();});});}
    private void emit(byte[] data,Runnable next){if(!connected||hid==null||host==null){pendingStroke=null;strokeDone=null;releaseWake();return;}sendReport(data,next,0);}
    private void sendReport(byte[] data,Runnable next,int attempt){if(!connected||hid==null||host==null){pendingStroke=null;strokeDone=null;releaseWake();return;}try{if(hid.sendReport(host,0,data)){if(next!=null)later(12,next);return;}if(attempt<4){later(35,()->sendReport(data,next,attempt+1));return;}fail("Bluetooth rejected the keyboard report. Reconnect and try again.");}catch(Exception e){if(attempt<4){later(35,()->sendReport(data,next,attempt+1));}else fail("Keyboard report failed. Reconnect and try again.");}}
    public void adapterChanged(int s){exec(()->{if(s==BluetoothAdapter.STATE_OFF||s==BluetoothAdapter.STATE_TURNING_OFF){loss("Bluetooth is off.");candidates.clear();}else if(s==BluetoothAdapter.STATE_ON){state=State.DISCONNECTED;message="Bluetooth is available. Search and connect explicitly.";acquire();publish();}});}
    public void close(){exec(()->{closed=true;cancelInput();try{if(hid!=null&&registered)hid.unregisterApp();if(adapter!=null&&hid!=null)adapter.closeProfileProxy(BluetoothProfile.HID_DEVICE,hid);}catch(Exception ignored){}thread.quitSafely();});}
}
